name: RestSharp Quiz CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "30 13 * * 4"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./RestSharpQuiz
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --settings:quizHeroku.runsettings

    - name: use this action, test solution dir
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: ./RestSharpQuiz.Tests
        report_name: my_project_tests
        report_title: My Project Tests
